# This is a basic workflow to help you get started with Actions

name: Integración y entrega continua.


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      NOMBRES: "JOHNNY RICHARD"    
      APELLIDOS: "QUISPE TICONA"  
      EDAD: "37"             
      user: ${{secrets.USER}}
      password: ${{secrets.PASSWORD}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # PRIMER STEP: PRESENTACION
      - name: PRESENTACION
        run: |
          echo Impresion de mis datos:
          echo "Nombres: $NOMBRES"
          echo "Apellidos: $APELLIDOS"
          echo "Edad: $EDAD"
      # SEGUNDO STEP: DATOS GENERALES
      - name: DATOS GENERALES
        run: |
          echo "carrera de ingeniería de sistemas"
      #  TERCER STEP: VARIABLES DE ENTORNO SECRETAS
      - name: VARIABLES DE ENTORNO SECRETAS
        run: |
          echo user: ${{env.user}}
          echo password: ${{env.password}}

      # VARIABLE ABIERTA
      - name: VERSION DE MI PROYECTO
        run: |
          echo "Variable abierta: ${{vars.VALOR}}"
          
